"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PacketID = void 0;
//
var PacketID;
(function (PacketID) {
    PacketID[PacketID["CS_PING"] = 1001] = "CS_PING";
    PacketID[PacketID["CS_LOBBY_SEARCHING_ENEMY"] = 1002] = "CS_LOBBY_SEARCHING_ENEMY";
    PacketID[PacketID["CS_LOBBY_SEARCHING_RESULT"] = 1003] = "CS_LOBBY_SEARCHING_RESULT";
    PacketID[PacketID["CS_LOBBY_SEARCHING_CANCEL"] = 1004] = "CS_LOBBY_SEARCHING_CANCEL";
    PacketID[PacketID["CS_GAME_ENTRY"] = 1005] = "CS_GAME_ENTRY";
    PacketID[PacketID["CS_GAME_READY"] = 1006] = "CS_GAME_READY";
    PacketID[PacketID["CS_GAME_START"] = 1007] = "CS_GAME_START";
    PacketID[PacketID["CS_GAME_COMPUTE"] = 1008] = "CS_GAME_COMPUTE";
    PacketID[PacketID["CS_GAME_TURN"] = 1009] = "CS_GAME_TURN";
    PacketID[PacketID["CS_GAME_SELECT"] = 1010] = "CS_GAME_SELECT";
    PacketID[PacketID["CS_GAME_RESULT"] = 1011] = "CS_GAME_RESULT";
    PacketID[PacketID["CS_GAME_NEW_MATCH"] = 1012] = "CS_GAME_NEW_MATCH";
    PacketID[PacketID["CS_GAME_OUT"] = 1013] = "CS_GAME_OUT";
    PacketID[PacketID["CS_GAME_TIMER"] = 1014] = "CS_GAME_TIMER";
    PacketID[PacketID["SC_PING"] = 3001] = "SC_PING";
    PacketID[PacketID["SC_LOBBY_SEARCHING_ENEMY"] = 3002] = "SC_LOBBY_SEARCHING_ENEMY";
    PacketID[PacketID["SC_LOBBY_SEARCHING_RESULT"] = 3003] = "SC_LOBBY_SEARCHING_RESULT";
    PacketID[PacketID["SC_LOBBY_SEARCHING_CANCEL"] = 3004] = "SC_LOBBY_SEARCHING_CANCEL";
    PacketID[PacketID["SC_GAME_ENTRY"] = 3005] = "SC_GAME_ENTRY";
    PacketID[PacketID["SC_GAME_READY"] = 3006] = "SC_GAME_READY";
    PacketID[PacketID["SC_GAME_START"] = 3007] = "SC_GAME_START";
    PacketID[PacketID["SC_GAME_COMPUTE"] = 3008] = "SC_GAME_COMPUTE";
    PacketID[PacketID["SC_GAME_TURN"] = 3009] = "SC_GAME_TURN";
    PacketID[PacketID["SC_GAME_SELECT"] = 3010] = "SC_GAME_SELECT";
    PacketID[PacketID["SC_GAME_RESULT"] = 3011] = "SC_GAME_RESULT";
    PacketID[PacketID["SC_GAME_NEW_MATCH"] = 3012] = "SC_GAME_NEW_MATCH";
    PacketID[PacketID["SC_GAME_OUT"] = 3013] = "SC_GAME_OUT";
    PacketID[PacketID["SC_GAME_TIMER"] = 3014] = "SC_GAME_TIMER";
})(PacketID = exports.PacketID || (exports.PacketID = {}));
